In [1]:
import numpy as np
import random

In [2]:
# creat linearly separable data set, set num = 10, the dim of n = 10
# the function of separating hyperplane is w * x + b == 0

def creat_data(num=10, dim=10):
    b = np.random.rand(1)
    w = np.random.rand(dim)
    x = np.random.uniform(-50, 50, (num,dim))  # the range of the value of x is [-50,50]

    y_label = np.zeros(num)
    for i in range(num):
        if np.dot(x[i], w) + b >= 0:
            y_label[i] = 1
        else:
            y_label[i] = -1
    return(x, y_label)

In [3]:
def sign(w, x, b):
    if np.dot(w,x)+b >=0:
        return 1
    else:
        return -1

In [4]:
# primal form

num = 10
dim = 10
x, y_label = creat_data(num, dim)

lr = 0.1  # learning rate
w = np.zeros(dim) # initial weight vector
b = 0 # initial bias
sort_correct = np.zeros(num,bool)

while not sort_correct.all():
    for i in range(num):
        if sign(w, x[i], b) == y_label[i]:
            sort_correct[i] = True
        else:
            w += lr * y_label[i] * x[i]
            b += lr * y_label[i]
            sort_correct = np.zeros(num,bool)
            break
print('w =', w)
print('b =', b)

w = [ 1.37803924  1.22425656  1.13542506  2.92268316  3.13930876 10.27844504
 -0.98400195  9.49109126  7.48722119  1.10697569]
b = -0.20000000000000004


In [5]:
# check the code with the example2.1 in book

x = np.array([[3, 3], [4, 3], [1, 1]])
y_label = np.array([1, 1, -1])
num = 3
dim = 2

lr = 1  # learning rate
w = np.zeros(dim) # initial weight vector
b = 0 # initial bias

for i in [0, 2, 2, 2, 0, 2, 2]:
    if y_label[i] * (np.dot(w, x[i]) + b) <= 0:
        w += lr * y_label[i] * x[i]
        b += lr * y_label[i]
        print('w', w, 'b', b)

w [3. 3.] b 1
w [2. 2.] b 0
w [1. 1.] b -1
w [0. 0.] b -2
w [3. 3.] b -1
w [2. 2.] b -2
w [1. 1.] b -3


In [6]:
# dual form

num = 10
dim = 10
x, y_label = creat_data(num, dim)

lr = 0.1  # learning rate
alpha = np.zeros(num)
b = 0 # initial bias
sort_correct = np.zeros(num,bool)

Gram_matrix = np.dot(x,x.T)

while not sort_correct.all():
    for i in range(num):
        if y_label[i] * ((alpha * y_label * Gram_matrix[i]).sum() + b) > 0:
            sort_correct[i] = True
        else:
            alpha[i] += lr 
            b += lr * y_label[i]
            sort_correct = np.zeros(num,bool)
            break
            
print('alpha =', alpha)
print('b =', b)


alpha = [0.1 0.1 0.1 0.  0.1 0.1 0.  0.  0.  0. ]
b = 0.1


In [7]:
# check the code with the example2.2 in book

x = np.array([[3, 3], [4, 3], [1, 1]])
y_label = np.array([1, 1, -1])
num = 3

lr = 1  # learning rate
alpha = np.zeros(num)
b = 0 # initial bias

Gram_matrix = np.dot(x,x.T)
print('Gram_matrix\n',Gram_matrix)

for i in [0, 2, 2, 2, 0, 2, 2]: # because index begins from 0 in python
    if y_label[i] * ((alpha * y_label * Gram_matrix[i]).sum() + b) <= 0:
            alpha[i] += lr 
            b += lr * y_label[i]
            print('alpha',alpha,'b',b)

Gram_matrix
 [[18 21  6]
 [21 25  7]
 [ 6  7  2]]
alpha [1. 0. 0.] b 1
alpha [1. 0. 1.] b 0
alpha [1. 0. 2.] b -1
alpha [1. 0. 3.] b -2
alpha [2. 0. 3.] b -1
alpha [2. 0. 4.] b -2
alpha [2. 0. 5.] b -3
